repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://gitlab.com/jvenom/elixir-pre-commit-hooks
    rev: v1.0.0
    hooks:
      - id: mix-format
